[package]
name = "macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.36"
syn = { version = "2.0.63", features = [
  "full",
  "parsing",
  "printing",
  "proc-macro",
] }
